name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_DEPS: cmake libconfig++-dev libxxhash-dev libjemalloc-dev libtsl-hopscotch-map-dev pkg-config python3-jinja2
  TEST_DEPS: bc bats clang node-d3 graphviz moreutils fakeroot
jobs:
  build-on-macos:
    env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        XML_CATALOG_FILES: /opt/homebrew/etc/xml/catalog
    strategy:
      matrix:
        os: [macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - name: check if SIP is enabled on this runner
      run: |
        csrutil status | grep "System Integrity Protection status: disabled"
    - uses: actions/checkout@v3
    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: build-on-macos-12
    - name: install-deps
      run: |
        brew update
        # brew often fails due to existing files, hence the --overwrite parameter and the retry
        brew bundle -f || (for v in 3.11 3.12; do brew link --overwrite python@${v} ; done; brew bundle -f)
    - name: configure vm
      run: |
        # library validation would prevent loading libfirebuild to some binaries
        sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
    - name: build-out-of-tree
      run: |
        if [ ${{ matrix.os }} = macos-14 ]; then
          HOMEBREW_PREFIX=/opt/homebrew
        else
          HOMEBREW_PREFIX=/usr/local
          export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
        fi
        export PATH=${HOMEBREW_PREFIX}/opt/ccache/libexec:$PATH
        export PYTHONPATH=$(ls -d ${HOMEBREW_PREFIX}/lib/python*/site-packages | tail -n1)
        cmake -DCMAKE_BUILD_TYPE=Debug -B build-make
        make -C build-make -j$(getconf _NPROCESSORS_ONLN)
    - name: test
      run: |
        # tests are failing on m1 due to missing arm64e ABI configuration: https://github.com/actions/runner-images/issues/9461
        make -C build-make check || [ ${{ matrix.os }} = macos-14 ]
    - name: install firebuild
      run: |
        sudo make -C build-make install
    - name: build-with-xcode
      run: |
        if [ ${{ matrix.os }} = macos-14 ]; then
          HOMEBREW_PREFIX=/opt/homebrew
        else
          HOMEBREW_PREFIX=/usr/local
          export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
        fi
        export PATH=${HOMEBREW_PREFIX}/opt/ccache/libexec:$PATH
        export PYTHONPATH=$(ls -d ${HOMEBREW_PREFIX}/lib/python*/site-packages | tail -n1)
        cmake -G Xcode -B build-xcode
        cd build-xcode
        xcodebuild

