name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_DEPS: cmake libconfig++-dev libxxhash-dev libjemalloc-dev libtsl-hopscotch-map-dev pkg-config python3-jinja2
  TEST_DEPS: bc bats clang node-d3 graphviz moreutils fakeroot
jobs:

  build-on-freebsd:
    needs: style-checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.0.6
      with:
        usesh: true
        mem: 2048
        prepare: |
          git config --global --add safe.directory $PWD
          pkg install -y cmake pkgconf docbook-xsl gmake bats-core py39-jinja2 python3 libconfig xxhash git
          (cd .. && git clone https://github.com/Tessil/hopscotch-map.git && cd hopscotch-map/ && cmake . && make install)
        run: |
             export XML_CATALOG_FILES=/usr/local/share/xml/catalog
             cmake -DCMAKE_CXX_FLAGS="-I/usr/local/include" -DCMAKE_BUILD_TYPE=Debug .
             make
             make check

  style-checks:
    runs-on: ubuntu-22.04
    outputs:
      week: ${{ steps.week-of-year.outputs.week }} # map step output to job output
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v3
    - name: install-deps
      run: |
        # TODO(rbalint) use packaged cpplint when it becomes available https://bugs.debian.org/960847
        pip3 install cpplint==1.5.4
    - name: style-check
      run: env PATH=$HOME/.local/bin:$PATH cpplint --recursive src test
      # this will be used by other jobs to invalidate cache after a week
    - name: week of year
      id: week-of-year
      run: echo "week=$(/bin/date -u "+%V")" >> $GITHUB_OUTPUT
